# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc479c6df274825d1317c6ba43086c0f8bd50da8b9d4994d682aec8e6de77fb8b96fcc8aa379e6f11473fdad53557966b387daa4a6aef6c7504ba15540f7ddff

test:
  secret_key_base: 7fb227d380659e52180b6c61c133123c115f41ec51c663e21c04062089fbb8abf4eed756460c434b48747b6c43dc3e83cc772052d0efbee9c87a07977daf55ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
